name: Test using Pytest

on:
  workflow_call:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @devcontainers/cli@v0.30.0
      - run: devcontainer up --workspace-folder=.
      - name: Diagnose cluster state
        run: |
          devcontainer exec --workspace-folder=. kubectl get nodes -o wide
          devcontainer exec --workspace-folder=. kubectl get pods -A
          devcontainer exec --workspace-folder=. cilium status
          devcontainer exec --workspace-folder=. minikube status
      - run: devcontainer exec --workspace-folder=. uv run pytest -rA -x --color=yes
